### ISSUE TITLE
Typescript errors - TypeError: QuickLRU is not a constructor

### ISSUE THREAD

**Issue by perbergland** [sindresorhus/quick-lru#15]
I tried using this package (v ^4.0.1) but get runtime errors when using it from typescript:

```
import QuickLRU = require("quick-lru");

...

const userCache = new QuickLRU<
  string,
  { data: UserEntities.User | undefined; maxAge: number }
>({ maxSize: 300 });


TypeError: QuickLRU is not a constructor
```

**Comment by sindresorhus** [comment]
It works fine in the type tests: https://github.com/sindresorhus/quick-lru/blob/16d15d470a8eb87c2a7dd5b80892d9b74f1acd3c/index.test-d.ts#L2 Must be something with your TS config.
