### ISSUE TITLE
`.entries` method

### ISSUE THREAD

**Issue by silverwind** [sindresorhus/quick-lru#25]
There are `.keys` and `.values` methods mimicking the same-named `Object` methods, but not there seems to be no equivalent of [Object.entries](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/entries) which I think might be handy sometimes. It should return a iterable of `[key, value]`.

**Comment by sindresorhus** [comment]
From the docs:

> The instance is iterable so you can use it directly in a for…of loop.

```js
for (const [key, value] of lru) {
 // ...
}
```

**Comment by silverwind** [comment]
Ah missed that part, sorry.
