### ISSUE TITLE
Explicit maxAge in set() is stored as relative

### ISSUE THREAD

**Issue by mwojnars** [sindresorhus/quick-lru#35]
It seems that `maxAge` argument is used incorrectly in the code of `set()`: the addition of `Date.now()` is present only for a default `this.maxAge`, but missing when an explicit `maxAge` was provided, which results in assigning a relative [ms] value to `expiry` instead of an absolute timestamp value.

https://github.com/sindresorhus/quick-lru/blob/6ee4b6e9a7391f4536324ea1df909839d5d2734d/index.js#L113

**Comment by alextes** [comment]
Let's add a test for this too haha, spent 30min going, what is going on 🙃 ?? As it took me a while to start questioning the assumption that simply setting a `maxAge` correctly did not work 😅 .

Thanks for a great library!

**Comment by sindresorhus** [comment]
// @javi11

**Comment by alextes** [comment]
ooooh, well "correctly" is debatable here. Seems from the test the option is intended to be used as a timestamp, not a duration in milliseconds.

I'd suggest we either:
1. not use the same name for an option that on the one hand takes a number of milliseconds to keep the item in cache before expiring, and on the other hand takes a timestamp that indicates when to expire the item.
2. accept a number of milliseconds to keep the item in cache in both cases.

fwiw 2. has my preference.

**Comment by javi11** [comment]
You are right @alextes bad concept there,  I Will release a fix usong the second option as soon I have some free time ;)
