### ISSUE TITLE
feat: if third argument is a number to `set(key, value, opts || maxAge)`, then assume it is `maxAge`

### ISSUE THREAD

**Issue by titanism** [sindresorhus/quick-lru#42]
In <https://github.com/sindresorhus/quick-lru/blob/771392878fc0e2325b1172d04260e87afe94c8f7/index.js#L115> you can see that the third argument must be an object.  However for 1:1 compatibility with other stores, e.g. `ioredis`, it would be nice (and backwards compatible) if you pass a third argument that is not an Object, but a Number.  If a Number, it would be inferred as `options.maxAge` value.

**Comment by sindresorhus** [comment]
I'm not interested in this, sorry. I don't want my API to be worse just to be compatible with another random package.
