### ISSUE TITLE
oldCache加个设置项可以关闭

### ISSUE THREAD

**Issue by Xfinland** [sindresorhus/quick-lru#44]
引用这个库目的：优化存储性能，自动释放长期不用的数据。（我认为大多数用户的想法）
看了下源码，咋还有个oldCache,偷偷把所有的数据保留了一份。
建议：
方案一： 加个option,可以设置不需要保留oldCache
方案二：直接删掉oldCache

**Comment by sindresorhus** [comment]
English-only
