### ISSUE TITLE
Documentation for `.set` is wrong.

### ISSUE THREAD

**Issue by mstade** [sindresorhus/quick-lru#45]
Hi! Lovely library, thank you for sharing it with the world!

The documentation for `.set` states:

> .set(key, value, options?)
>
> Set an item. **Returns the instance.**

(Emphasis mine.) This seems to be wrong – `.set` doesn't actually return anything. It would be rather handy if it returned the `value` though, it'd allow for things like:

```js
const thing = lru.get(key) ?? lru.set(key, getThing())
```

Returning the instance would work too I suppose, it'd be a bit awkward but still:

```js
const thing = lru.get(key) ?? lru.set(key, getThing()).get(key)
```

Either way, `.set` doesn't actually return anything so the docs seem to be wrong.

**Comment by sindresorhus** [comment]
Fixed.

I'm open to adding a `getOrSet()` method.
