### ISSUE TITLE
How to get the `maxSize` of a cache instance?

### ISSUE THREAD

**Issue by tbontb-iaq** [sindresorhus/quick-lru#47]
```typescript
const cache = new QuickLRU({ maxSize: 10 });

/// cache.maxSize ???
```

When using `resize` to update `maxSize`, you may need to compare the new and old maxSizes.

**Comment by tbontb-iaq** [comment]
Quick job.
It can be obtained through `maxSize`, but it must be set through `resize`.
Is it better to define the getter and setter for `maxSize`?

**Comment by sindresorhus** [comment]
Yeah, not worth removing `resize`, but we could make `maxSize` setter just call it internally.
