### ISSUE TITLE
Support also CommonJS

### ISSUE THREAD

**Issue by jfoclpf** [sindresorhus/quick-lru#50]
Do you think it would be possible to accept also CommonJS? 

```js
const QuickLRU = require('quick-lru')
```

I can make the PR if it's ok for you.

We have a huge project that started with CommonJS; moving everything to ESM would be a big hassle, and node doesn't allow to combine both.

Thank you

**Comment by sindresorhus** [comment]
https://joyeecheung.github.io/blog/2024/03/18/require-esm-in-node-js/

**Comment by jfoclpf** [comment]
@sindresorhus 

option `--experimental-detect-module` is not yet available

in the meantime do you suggest any workaround?
