### ISSUE TITLE
Published transpiled source

### ISSUE THREAD

**Issue by skeggse** [sindresorhus/quick-lru#7]
The `class` syntax is available in node 6+, and modern browsers, but isn't supported by uglify. Could we publish a transpiled copy of `quick-lru` in npm for older targets/minification? That's the recommendation I've sometimes seen, as you might have many many dependencies and transpiling all of them whenever you make a change to your application can take unnecessary time. It's also what [rollup-plugin-babel recommends](https://github.com/rollup/rollup-plugin-babel#external-dependencies), for what it's worth.

**EDIT:** I just noticed that `quick-lru` very recently deprecated support for node <6, but I think this is still worth considering given that some automated tools may not support anything more than es5 syntax.

**Comment by sindresorhus** [comment]
This module mainly targets Node.js, not the browser. It's up to you to transpile it with Babel if you want to use it in the browser. You can find a more detailed explanation here: https://github.com/sindresorhus/ama/issues/446

If you use Webpack, check out [`babel-engine-plugin`](https://github.com/SamVerschueren/babel-engine-plugin), which transpiles only the dependencies that needs to be transpiled.

**Comment by waynesbrain** [comment]
Looking for the answer on this today and after considering the source I tried simply pasting the raw QuickLRU class from github directly into DevTools console and it works just fine. No transpiling needed.
